name: evading_button_game
description: A game with evading buttons and celebrations.

publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  lottie: ^2.7.0
  confetti: ^0.7.0
  vibration: ^1.7.5
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  analyzer: ^4.7.0
  win32: ^5.3.0 # Versão mais recente
  vibration: ^1.7.5


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/evading_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/sounds/
